on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      local-dir: C:\wamp64\www\CarleeBackend\
      server-dir: /carlee/
      with:
        server: node15-fr.n0c.com
        username: contact@lisa-tallet.mds-nantes.yt
        password: ${{ secrets.ftp_password }}
        port: 21
